    CREATE TABLE accounts (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(22) NOT NULL,
        mail VARCHAR(22) NOT NULL UNIQUE,
        password VARCHAR(22) NOT NULL
    );

CREATE TABLE settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steamUser VARCHAR(22),
    gogUser VARCHAR(22),
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES accounts(id)
);

INSERT INTO accounts (name, mail, password) VALUES ('Wompus', 'dick.balls@urmum.com', '1234');
INSERT INTO settings (steamUser, gogUser) VALUES (null ,null);